version: '3.9'
services:
  postgres:
    image: postgres:15.3
    ports:
      - "11432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: postgres
    volumes:
      - sandbox-postgres-volume:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  sandbox-postgres-volume:
