// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: v2/hello-world.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExistingField string `protobuf:"bytes,1,opt,name=existingField,proto3" json:"existingField,omitempty"`
	NewField      string `protobuf:"bytes,2,opt,name=newField,proto3" json:"newField,omitempty"`
}

func (x *HelloWorld) Reset() {
	*x = HelloWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_hello_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld) ProtoMessage() {}

func (x *HelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hello_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld.ProtoReflect.Descriptor instead.
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return file_v2_hello_world_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorld) GetExistingField() string {
	if x != nil {
		return x.ExistingField
	}
	return ""
}

func (x *HelloWorld) GetNewField() string {
	if x != nil {
		return x.NewField
	}
	return ""
}

var File_v2_hello_world_proto protoreflect.FileDescriptor

var file_v2_hello_world_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x32, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x76, 0x32, 0x22, 0x4e, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x62, 0x2d, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_hello_world_proto_rawDescOnce sync.Once
	file_v2_hello_world_proto_rawDescData = file_v2_hello_world_proto_rawDesc
)

func file_v2_hello_world_proto_rawDescGZIP() []byte {
	file_v2_hello_world_proto_rawDescOnce.Do(func() {
		file_v2_hello_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_hello_world_proto_rawDescData)
	})
	return file_v2_hello_world_proto_rawDescData
}

var file_v2_hello_world_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_hello_world_proto_goTypes = []interface{}{
	(*HelloWorld)(nil), // 0: helloworld.v2.HelloWorld
}
var file_v2_hello_world_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_hello_world_proto_init() }
func file_v2_hello_world_proto_init() {
	if File_v2_hello_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_hello_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_hello_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_hello_world_proto_goTypes,
		DependencyIndexes: file_v2_hello_world_proto_depIdxs,
		MessageInfos:      file_v2_hello_world_proto_msgTypes,
	}.Build()
	File_v2_hello_world_proto = out.File
	file_v2_hello_world_proto_rawDesc = nil
	file_v2_hello_world_proto_goTypes = nil
	file_v2_hello_world_proto_depIdxs = nil
}
