output = "pkg/infra/models"
wipe = true
no-tests = true

[psql]
schema = "app_default"
dbname = "sandbox_db"
host = "postgres"
port = 5432
user = "test_user"
pass = "password"
sslmode = "disable"
blacklist = ["migrations"]
